### ISSUE TITLE
How to use subscribeAsync and show messages ?

### ISSUE THREAD

**Issue by S3yll** [Netina/Netina.Stomp.Client#1]
Hi,

How do you show messages you receive ? I'm trying to subscribe on a topic but nothing happens.
Could you explain how to use your subscribeAsync function ?

Thank you in advance,
S3yll

**Comment by mrmohande3** [comment]
when u subscribe on a method ( like : /user/queue/support/typing ) you set an event handler like a method in like : 
```
await _client.SubscribeAsync<StompIsTyping>("/user/queue/support/typing", new Dictionary<string, string>(),
                (sender, message) =>
                {
                    IsTypingReceived?.Invoke(sender, message);

                });
```
i set an event handler end of method , so when i receive message from this url that event will fire and i get the message
