### ISSUE TITLE
notwork with activemq

### ISSUE THREAD

**Issue by khanorder** [Netina/Netina.Stomp.Client#4]
The websoket maybe need to subprtocol stomp on Apache ActiveMQ.

Could you update for I can emplement the member variable 'Subprotocol' in System.Net.Websocket?

**Comment by khanorder** [comment]
I solved this issue.

When the Websocket client was generated, add subprotocol to member 'Options' of the Websocket member.

This is my code.

`
_socket = new WebsocketClient(new Uri(url), () => {
    var ws = new ClientWebSocket();
    ws.Options.AddSubProtocol("stomp");
    return ws;
})
{
    ReconnectTimeout = reconnectTimeOut,
    IsReconnectionEnabled = reconnectEnable,
    ErrorReconnectTimeout = TimeSpan.FromSeconds(2.0),
};
`

**Comment by JanMarkovich** [comment]
@mrmohande3 May you publish package with last changes, please?

**Comment by mrmohande3** [comment]
yes sure

**Comment by mrmohande3** [comment]
package has been update to 2.0.5
